# TensorFlow Basics

In [1]:
import tensorflow as tf

In [3]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.8.0


## Tensors
Tensor means vector.

In [4]:
hello = tf.constant('Hello')

In [7]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [8]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [15]:
world = tf.constant(' World')

In [16]:
result = hello + world

In [17]:
result

<tf.Tensor 'add_2:0' shape=() dtype=string>

In [18]:
type(result)

tensorflow.python.framework.ops.Tensor

In [19]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [20]:
result

b'Hello World'

## Computations

In [30]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [31]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [32]:
tensor_1 + tensor_2

<tf.Tensor 'add_7:0' shape=() dtype=int32>

In [33]:
with tf.Session() as sess:
    result = sess.run(tensor_1 + tensor_2)
result

3

In [34]:
sess.close()

## Operations

In [35]:
const = tf.constant(10)

In [36]:
fill_mat = tf.fill((4,4),10)

In [37]:
with tf.Session() as sess:
    result = sess.run(fill_mat)
print(result)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [38]:
myzeros = tf.zeros((4,4))

In [39]:
myones = tf.ones((4,4))

In [40]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [41]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [42]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [43]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [44]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.34062248  0.4258762   0.18725184  0.01065622]
 [ 0.3324776  -0.36027163  0.23724586 -0.8898441 ]
 [ 1.1856436   0.39400363  0.61025625 -0.5897672 ]
 [-0.48109487  0.59296197 -0.67810714  0.65307367]]


[[0.22440064 0.98126817 0.9120728  0.9117775 ]
 [0.4915471  0.33317924 0.3278016  0.30147362]
 [0.90585434 0.8810935  0.67362475 0.8541037 ]
 [0.85933757 0.4801396  0.2597537  0.46403325]]




## Matrix Multiplication

In [45]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [46]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [47]:
b = tf.constant([[10],[100]])

In [48]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [49]:
result = tf.matmul(a,b)

In [50]:
result.eval()

array([[210],
       [430]])